// Generated by CoffeeScript 1.8.0

/*
 * New coffeescript file
 */

(function() {
  var MarkerModel;

  MarkerModel = (function() {
    function MarkerModel(map, lat, long, html, title) {
      this.html = html;
      this.position = new google.maps.LatLng(lat, long);
      this.marker = new google.maps.Marker({
        position: this.position,
        map: map,
        title: title
      });
    }

    MarkerModel.prototype.getObject = function() {
      var markerObj;
      markerObj = {
        html: this.html,
        position: this.position,
        googleMarker: this.marker
      };
      return markerObj;
    };

    return MarkerModel;

  })();

  this.MapWrapper = (function() {
    var addListener, generateHtmlForAd;

    function MapWrapper() {
      var boundsListener, mapOptions;
      this.infoWindow = new google.maps.InfoWindow();
      this.bounds = new google.maps.LatLngBounds();
      mapOptions = {
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      this.map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
      this.map.setTilt(45);
      boundsListener = google.maps.event.addListener(this.map, 'bounds_changed', function() {
        this.setZoom(14);
        return google.maps.event.removeListener(boundsListener);
      });
    }

    MapWrapper.prototype.addMarkerForAd = function(ad, lat, long) {
      var adHtml, currentMarker, model;
      adHtml = generateHtmlForAd(ad);
      model = new MarkerModel(this.map, lat, long, adHtml, 'titile');
      currentMarker = model.getObject();
      if ((currentMarker != null)) {
        addListener(this.map, this.infoWindow, currentMarker);
        this.bounds.extend(currentMarker.position);
        return this.map.fitBounds(this.bounds);
      }
    };

    MapWrapper.prototype.refresh = function() {
      return google.maps.event.trigger(this.map, 'resize');
    };

    addListener = function(map, infoWindow, marker) {
      var googleMarker, html;
      googleMarker = marker.googleMarker;
      html = marker.html;
      return google.maps.event.addListener(googleMarker, 'click', function() {
        infoWindow.setContent(html);
        return infoWindow.open(map, googleMarker);
      });
    };

    generateHtmlForAd = function(ad) {
      var html;
      return html = '<div class="info_content">' + '<h3>' + ad.title + '</h3>' + '<p>' + ad.desc + '</p>' + '</div>';
    };

    return MapWrapper;

  })();

}).call(this);
